export const dummySkillUsers = {
    "Programming": [
        {
            id: '1',
            name: 'Benjamin Engel',
            title: 'Java Developer',
            experience: '5 Years',
            rating: 4,
            likes: '5K+',
            swaps: '2K+',
            comments: 128,
            image: require('../assets/java_developer.webp'),
        },
        {
            id: '2',
            name: 'Ramesh Pathak',
            title: 'RN Developer',
            experience: '5 Years',
            rating: 5,
            likes: '100K+',
            swaps: '5K+',
            comments: 100,
            image: require('../assets/programmer.jpg'),
        },
        {
            id: '3',
            name: 'John Sharma',
            title: 'JS Developer',
            experience: '5 Years',
            rating: 3,
            likes: '100K+',
            swaps: '5K+',
            comments: 100,
            image: require('../assets/programmer.jpg'),
        },
        {
            id: '4',
            name: 'Leo Morgan',
            title: 'Software Arch',
            experience: '5 Years',
            rating: 2,
            likes: '100K+',
            swaps: '5K+',
            comments: 100,
            image: require('../assets/programmer.jpg'),
        },

    ],
    "Graphic Designer": [
        {
            id: '5',
            name: 'Sophia Clark',
            title: 'UI/UX Designer',
            experience: '3 Years',
            rating: 5,
            likes: '3.2K+',
            swaps: '1.5K+',
            comments: 76,
            image: require('../assets/graphic_designer.png'),
        },
    ],
    "Cooking": [
        {
            id: '6',
            name: 'Liam Turner',
            title: 'Chef',
            experience: '4 Years',
            rating: 4,
            likes: '4.1K+',
            swaps: '2.7K+',
            comments: 98,
            image: require('../assets/cooking.webp'),
        },
    ], 
    "Coder": [
        {
            id: '7',
            name: 'James Smith',
            title: 'Python Developer',
            experience: '4 Years',
            rating: 4,
            likes: '4.1K+',
            swaps: '2.7K+',
            comments: 77,
            image: require('../assets/coder.jpg'),
        },
    ],
    "Dancer": [
        {
            id: '8',
            name: 'David Brown',
            title: 'Dance Teacher',
            experience: '4 Years',
            rating: 4,
            likes: '4.1K+',
            swaps: '2.7K+',
            comments: 77,
            image: require('../assets/dancer.jpeg'),
        },
    ],
}


